[package]
name = "git-credential-1password-cli"
version = "0.2.2"
edition = "2024"
authors = ["Kevin Deng"]
description = "A Git credential helper that integrates with 1Password CLI"
license = "MIT"
repository = "https://github.com/sxzz/git-credential-1password-cli"
homepage = "https://github.com/sxzz/git-credential-1password-cli#readme"

[dependencies]
clap = { version = "^4.5.53", features = ["derive"] }
